version: '3.8'

services:
  web:
    build: .
    ports:
      - "1028:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=ctf_challenge
      - DB_USER=root
      - DB_PASS=${DB_PASS}
    env_file:
      - .env

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ctf_challenge
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  db_data:
