version: '3.8'

services:
  app:
    build: .
    ports:
      - "1027:8080"  
    volumes:
      - .:/app  
      - /app/node_modules  
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge