version: '3.8'

services:
  access:
    build: ./access_overflow
    container_name: access
    networks:
      - pwn
    ports:
      - "1016:1016"
    cpus: '0.5'  # Limit to 0.5 CPU cores
    mem_limit: 512m  # Limit to 512 MB of RAM

  blind:
    build: ./blindfolded
    container_name: blind
    networks:
      - pwn
    ports:
      - "1017:1017"
    cpus: '0.5'
    mem_limit: 512m

  echo2:
    build: ./echo_chamber-v2
    container_name: echo2
    networks:
      - pwn
    ports:
      - "1019:1019"
    cpus: '0.5'
    mem_limit: 512m

  echo1:
    build: ./echo_chamber
    container_name: echo1
    networks:
      - pwn
    ports:
      - "1018:1018"
    cpus: '0.5'
    mem_limit: 512m

  leak:
    build: ./leak
    container_name: leak
    networks:
      - pwn
    ports:
      - "1020:1020"
    cpus: '0.5'
    mem_limit: 512m

  review:
    build: ./review_hub
    container_name: review
    networks:
      - pwn
    ports:
      - "1022:1022"
    cpus: '0.5'
    mem_limit: 512m

  syscal:
    build: ./syscalator
    container_name: syscal
    networks:
      - pwn
    ports:
      - "1023:1023"
    cpus: '0.5'
    mem_limit: 512m

  library:
    build: ./library
    container_name: library
    networks:
      - pwn
    ports:
      - "1021:1021"
    cpus: '0.5'
    mem_limit: 512m

networks:
  pwn:
