version: '3.8'

services:
  web:
    build: .
    ports:
      - "1032:80"
    volumes:
      - ./login.php:/var/www/html/login.php
      - ./style.css:/var/www/html/style.css
      - ./flitz.jpg:/var/www/html/flitz.jpg
      - ./S:/var/www/html/S
