# Use an official PHP Apache image as the base image
FROM php:7.4-apache

# Set the working directory to /var/www/html
WORKDIR /var/www/html

# Copy the PHP files, CSS, and image to the container
COPY login.php .
COPY style.css .
COPY flitz.jpg .
COPY S .
# Expose port 80
EXPOSE 80

# Start Apache in the foreground
CMD ["apache2-foreground"]