services:
  app:
    build:
      context: .
    container_name: ctf_app
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ctf_challenge

  mongodb:
    image: mongo:6.0
    container_name: ctf_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ctf_challenge
volumes:
  mongo_data:
