# Use the official Node.js image
FROM node:18

# Set the working directory
WORKDIR /

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy application code
COPY . .

# Expose the app port
EXPOSE 8083

# Run the app
CMD ["node", "index.js"]
