services:
  brain-rot:
    image: brain-rot
    container_name: brain-rot
    networks:
      - crypto
    ports:
      - "1235:1235"
    environment:
      - FLAG=FL1TZ{ma_n3ich_wala_tanya_f8yabou_:(}
  out-of-sight:
    image: out-of-sight
    container_name: out-of-sight
    networks:
      - crypto
    ports:
      - "1234:1234"
    environment:
      - FLAG=FL1TZ{n0t_sO_0ut_of_M1nd_ar3n't_wE}
  rsayo:
    image: rsayo
    container_name: rsayo
    networks:
      - crypto
    ports:
      - "1236:1236"
    environment:
      - FLAG=FL1TZ{A_2nD_X0R_h1t_th3_Ctf!!}
  rsayo-fast:
    image: rsayo-fast
    container_name: rsayo-fast
    networks:
      - crypto
    ports:
      - "1237:1237"
    environment:
      - FLAG=FL1TZ{A_2nD_X0R_h1t_th3_Ctf!!}
  lvl1:
    image: lvl1
    container_name: lvl1
    networks:
      - crypto
    ports:
      - "1401:1401"
    environment:
      - FLAG=FL1TZ{J3sS3_I_4M_Th3_1_wh0_N0nc3}
  lvl2:
    image: lvl2
    container_name: lvl2
    networks:
      - crypto
    ports:
      - "1402:1402"
    environment:
      - FLAG=FL1TZ{D1dn't_kn0w_s1Gn4tur3s_h4d_TH3m_51CK_m0v3S}
  lvl3:
    image: lvl3
    container_name: lvl3
    networks:
      - crypto
    ports:
      - "1403:1403"
    environment:
      - FLAG=FL1TZ{Try_th4t_1t_T4Rk0V_LABS}
  lvl4:
    image: lvl4
    container_name: lvl4
    networks:
      - crypto
    ports:
      - "1404:1404"
    environment:
      - FLAG=FL1TZ{LLLLLLLLLLLLLLL0O0O0OL}
  lvl1-fast:
    image: lvl1-fast
    container_name: lvl1-fast
    networks:
      - crypto
    ports:
      - "1411:1411"
    environment:
      - FLAG=FL1TZ{J3sS3_I_4M_Th3_1_wh0_N0nc3}
  lvl2-fast:
    image: lvl2-fast
    container_name: lvl2-fast
    networks:
      - crypto
    ports:
      - "1412:1412"
    environment:
      - FLAG=FL1TZ{D1dn't_kn0w_s1Gn4tur3s_h4d_TH3m_51CK_m0v3S}
  lvl3-fast:
    image: lvl3-fast
    container_name: lvl3-fast
    networks:
      - crypto
    ports:
      - "1413:1413"
    environment:
      - FLAG=FL1TZ{Try_th4t_1t_T4Rk0V_LABS}
  lvl4-fast:
    image: lvl4-fast
    container_name: lvl4-fast
    networks:
      - crypto
    ports:
      - "1414:1414"
    environment:
      - FLAG=FL1TZ{LLLLLLLLLLLLLLL0O0O0OL}

networks:
  crypto:
